name: mirrorchyan_uploading

on:
  workflow_dispatch:

jobs:

  mirrorchyan:
    runs-on: macos-latest
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "pyappify_dist/ok-gf2-win32-CPU.zip"
          mirrorchyan_rid: okgf2

          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ok-oldking
          repo: ok-gf2
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
