name: Push REPO

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*'

jobs:
  build:

    runs-on: windows-latest

    env:
      PYTHONIOENCODING: 'UTF-8'

    strategy:
      matrix:
        python-version: [ 3.12.6 ]

    steps:
      - name: Configure git
        run: |
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global user.email "ok-oldking@users.noreply.github.com"
          git config --global user.name "ok-oldking"
          echo "action_state=yellow" >> $env:GITHUB_ENV
          echo "${{ env.action_state }}"

      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set UTF-8 encoding
        run: |
          set PYTHONIOENCODING=utf-8
          set PYTHONLEGACYWINDOWSSTDIO=utf-8
          echo PYTHONIOENCODING=utf-8 >> $GITHUB_ENV

      - name: Get Changes between Tags
        id: changes
        uses: simbo/changes-between-tags-action@v1
        with:
          validate-tag: false

      - name: Get tag name
        id: tagName
        uses: olegtarasov/get-tag@v2.1.3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install cython setuptools

      - name: Copy ok-script lib
        run: |
          python -m ok.update.copy_ok_folder

      - name: Rename .py files to .pyx
        run: |
          Get-ChildItem -Path .\src -Recurse -Filter *.py -Exclude '__init__.py' | ForEach-Object { Rename-Item $_.FullName -NewName ($_.FullName -replace '\.py$', '.pyx') }

      - name: build cython
        run: |
          python setup.py build_ext --inplace
          Get-ChildItem -Path .\src -Recurse -Filter *.pyx | ForEach-Object { Remove-Item $_.FullName }
          Get-ChildItem -Path .\src -Recurse -Filter *.cpp | ForEach-Object { Remove-Item $_.FullName }

      - name: Run tests
        run: |
          Get-ChildItem -Path ".\tests\*.py" | ForEach-Object {
              Write-Host "Running tests in $($_.FullName)"
              python -m unittest $_.FullName
          }

      #      - name: push to cnb
      #        run: |
      #          python -m ok.update.push_repos --repos https://cnb:${{ secrets.CNB_TOKEN }}@cnb.cool/ok-oldking/ok-gf2.git --files deploy.txt --tag ${{ steps.tagName.outputs.tag }}

      - name: Build with PyAppify Action
        id: build-app
        uses: ok-oldking/pyappify-action@master

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          body: |
            ### 下载绿色版7z解压包, 解压后双击ok-gf2.exe, 下载后可应用内更新, 其他下载链接              
              * [Mirror酱下载渠道](https://mirrorchyan.com/zh/projects?rid=okgf2), 国内网页直链, 下载需要购买CD-KEY,
                已有Mirror酱CD-KEY可免费下载
              * [夸克网盘](https://pan.quark.cn/s/a1052cec4d13), 免费, 但需要注册并下载夸克网盘客户端
          files: ${{ steps.build-app.outputs.pyappify-assets }}

#      - name: Trigger MirrorChyanUploading
#        if: startsWith(github.ref, 'refs/tags/')
#        shell: bash
#        run: |
#          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan_uploading
#          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan_release_note
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
